### ISSUE TITLE
Question about GbfsLoader init rule (unique feed name policy)

### ISSUE THREAD

**Issue by tmiette** [entur/gbfs-loader-java#30]
Can you tell me with your are checking that the feed `name` is unique in `gbfs.json` ?
https://github.com/entur/gbfs-loader-java/blob/37d86fcb933291667c4942010ba296427c9c8f6e/src/main/java/org/entur/gbfs/GbfsLoader.java#L161

I am assuming that it is forbidden the the standard to have more that on feed with the same `name` in the same `language`, but it is not very clear.

https://github.com/NABSA/gbfs/blob/v2.2/gbfs.md#gbfsjson
> The gbfs.json discovery file SHOULD represent a single system or geographic area in which vehicles are operated.

**Comment by testower** [comment]
You're right that more than one feed with the same name is not an expected situation, and I can't think of a scenario where it would happen. Can you?

**Comment by tmiette** [comment]
It's something i'm facing with `gbfs.json` discovery file from one of our providers.

There are multiple sets of feeds of different regional areas (eg. `global` and `paris`) :
```json
{
    "data": {
        "en": {
            "feeds": [
                {
                    "name": "free_bike_status",
                    "url": "https://foo.bar/free_bike_status.json"
                },
                {
                    "name": "gbfs_versions",
                    "url": "https://foo.bar/gbfs_versions.json"
                },
                {
                    "name": "geofencing_zones",
                    "url": "https://foo.bar/geofencing_zones.json"
                },
                {
                    "name": "system_information",
                    "url": "https://foo.bar/system_information.json"
                },
                {
                    "name": "system_pricing_plans",
                    "url": "https://foo.bar/system_pricing_plans.json"
                },
                {
                    "name": "vehicle_types",
                    "url": "https://foo.bar/vehicle_types.json"
                },
                {
                    "name": "free_bike_status",
                    "url": "https://foo.bar/paris/free_bike_status.json"
                },
                {
                    "name": "geofencing_zones",
                    "url": "https://foo.bar/paris/geofencing_zones.json"
                },
                {
                    "name": "system_information",
                    "url": "https://foo.bar/paris/system_information.json"
                },
                {
                    "name": "system_pricing_plans",
                    "url": "https://foo.bar/paris/system_pricing_plans.json"
                },
                {
                    "name": "vehicle_types",
                    "url": "https://foo.bar/paris/vehicle_types.json"
                }
            ]
        }
    },
    "last_updated": 1648539684,
    "ttl": 0,
    "version": "2.2"
}
```

When asking them, they are telling me that there no limitation in GBFS standard about keys uniqueness in `gbfs.json` file. But I'm a bit confused about we are supposed to handle duplicated feed.

**Comment by testower** [comment]
While it is correct that the specification does not explicitly forbid duplicate names here, it still seems like it shouldn't happen, and that the specific use case here violates the following:

> The gbfs.json discovery file SHOULD represent a single system or geographic area in which vehicles are operated.

**Comment by tmiette** [comment]
I agree. Thanks for these clarifications.
